### ISSUE TITLE
Default `clonedUniforms` <coverage> user's `settings.uniforms` ❓

### ISSUE THREAD

**Issue by chinanf-boy** [vaneenige/phenomenon#3] opened 2018-07-17 02:36 UTC
https://github.com/vaneenige/phenomenon/blob/master/src/index.js#L363

``` js
instanceSettings.uniforms = Object.assign(settings.uniforms, clonedUniforms);
```

### Seem like The User `settings.uniforms` is not work, because It will be cover

**Comment by vaneenige** [comment] 2018-07-17 06:00
I've looked at the issue and it seems to work as intended, but I've tweaked it a little! In the piece of code below `this.uniforms` are those from the renderer that are passed to the instance. Those values will be assigned to the provided `settings.uniforms` or otherwise to an empty object.

```javascript
instanceSettings.uniforms = Object.assign(
  settings.uniforms || {},
  JSON.parse(JSON.stringify(this.uniforms)),
);
```

Have a look at the updated demo! Every instance there has its own progress uniform.

**Closed as completed** 2018-07-17 06:01 UTC
